[package]
name = "snp"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2"
inquire = "0.6.2"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
